version: '3'
services:
  web:
    build: .
    image: archimista
    command: rake db:setup && rake db:migrate && rails s -e development -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"